### ISSUE TITLE
Auto-use latest pyright

### ISSUE THREAD

**Issue by himat** [necaris/pre-commit-pyright#5]
Does this pre commit hook always use the latest pyright version or no?
Since to me it seems like it doesn't.

**Comment by wonjoonSeol-WS** [comment]
You are correct, it is using '1.1.53' version, so you can install pyright on your local machine and do this:
```
- repo: local
  hooks:
  - id: pyright
    name: pyright
    entry: pyright
    language: node
    types: [ python ]
    pass_filenames: false
```
